version: "0.1"
services :
  sesac-torch:
    image : euijin10/sesac-jenkins-test
    ports : 
      - 5001:5000
    volumes : 
      - /Users/sumin/Documents/sesac/docker:/home
    environment:
      - STAGE = DEV

